name: Hello World API Testing

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - run: npm install
      - run: npx playwright install

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      # Run Playwright Tests
      - name: Run Playwright Tests
        run: npm test

      # Upload test-results.json to S3
      - name: Upload test-results.json to S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/test-results/test-results.json s3://hello-world-api-test-reports/test_reports/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
