name: Hello World API Testing

on:
  push:
    branches: ["main"]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPORT_ID: "${{github.run_id}}"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install

      # - name: Install allure-playwright
      #   run: npm install allure-playwright

      # - name: Install allure-commandline
      #   run: npm install -D allure-commandline

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  
          aws configure set default.output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Start Node.js server
        run: npm start

      - name: Run Playwright Tests
        run: npm test
        continue-on-error: true

      - name: Generate Allure Reports
        run: npx allure generate $GITHUB_WORKSPACE/allure-results --clean

      - name: Upload Allure results to S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/allure-report/ s3://hello-world-api-reports/allure-report/report_${{ env.REPORT_ID }}/ --recursive

      - name: Get the public URL of S3 Bucket for ALLURE Report
        run: echo "https://hello-world-api-reports.s3.amazonaws.com/allure-report/report_${{ env.REPORT_ID }}/index.html"

      - name: Upload test-results.json to S3 for JSON Reports
        run: |
          aws s3 cp $GITHUB_WORKSPACE/test-results/test-results.json ${{vars.BUCKET_URL}}

      - name: Get the public URL of S3 Bucket for JSON Reports
        run: echo "${{vars.REPORTS_URL}}"

        # report url:- https://hello-world-api-reports.s3.amazonaws.com/allure-report/index.html

        # location url:- s3://hello-world-api-reports/allure-report
