name: Hello World API Testing

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  
          aws configure set default.output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Start Node.js server
        run: npm start

      - name: Run Playwright Tests
        run: npm test

      - name: Upload test-results.json to S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/test-results/test-results.json s3://hello-world-api-test-reports/test_reports/
